import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const Navbar = React.lazy(() => import("@/app/components/Navbar/Navbar"));
const TestProvider = React.lazy(() => import("@/app/context/TestContext"));
const SplashPovider = React.lazy(() => import("@/app/context/AppContext"));
const ShortCuts = React.lazy(() => import("@/app/components/ShortCuts/ShortCuts"));
const Footer = React.lazy(() => import("@/app/components/Footer/Footer"));
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Monkeytype Clone",
  description: "Generated by Sameh Hammad",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TestProvider>
        <SplashPovider>
          <body className={inter.className} suppressHydrationWarning={true}>
            <div className="w-full  min-h-screen bg-bgColor px-8 ">
              <Navbar />
              <div className="container min-w-full ">
                {children}
                <ShortCuts />
                <Footer />
              </div>
            </div>
          </body>
        </SplashPovider>
      </TestProvider>
    </html>
  );
}
